directories:
  output: dist-installer
  buildResources: assets
appId: com.dcscan.network
productName: DC Scan Network
files:
  - filter:
      - '**/*'
      - assets/bootstrap/**/*
      - assets/data/oui.txt
      - assets/
asarUnpack:
  - node_modules/oui/**/*
  - node_modules/mac-lookup/**/*
  - assets/data/**/*
win:
  icon: icons/dasscom.ico
  target:
    - target: nsis
      arch:
        - x64
  signAndEditExecutable: false
nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: DC Scan Network
  installerIcon: icons/dasscom.ico
  uninstallerIcon: icons/dasscom.ico
electronVersion: 37.2.6
