directories:
  output: dist-installer
  buildResources: assets
appId: com.dcscan.network
productName: DC Scan Network
files:
  - filter:
      - '**/*'
      - '!dist-installer/**/*'
      - '!node_modules/**/*'
      - node_modules/**/*
      - assets/**/*
      - assets/data/**/*
      - assets/data/oui.txt
      - config/**/*
      - config/device-mappings.json
asarUnpack:
  - node_modules/oui/**/*
  - node_modules/mac-lookup/**/*
  - assets/**/*
  - assets/data/**/*
  - assets/data/oui.txt
  - config/**/*
  - config/device-mappings.json
win:
  icon: dasscom/favicon.ico
  target:
    - target: nsis
      arch:
        - x64
  signAndEditExecutable: false
nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: DC Scan Network
  installerIcon: dasscom/favicon.ico
  uninstallerIcon: dasscom/favicon.ico
electronVersion: 37.2.6
